name: Proxmox Runner
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  proxmox:
    runs-on: machine/cpu=16/tenancy=spot

    steps:
      - uses: actions/checkout@v4

      - name: Install Localtonet + Run Proxmox
        run: |
          echo "[INFO] Installing Localtonet..."
          curl -fsSL https://localtonet.com/install.sh | sh

          echo "[INFO] Authenticating Localtonet..."
          localtonet --authtoken 2f56wyY9mdsVz7xMFuD4pXGhCgRBJEt3S

          echo "[INFO] Starting Proxmox container..."
          docker run -it --rm \
            --name proxmox \
            --hostname pve \
            --privileged \
            -e "PASSWORD=icyBe@r92" \
            -p 8006:8006 \
            -v "${PWD:-.}/data:/var/lib/vz" \
            -v "${PWD:-.}/config:/var/lib/pve-cluster" \
            --stop-timeout 120 \
            docker.io/dockurr/proxmox &

          echo "[INFO] Proxmox container is running"

          echo "[INFO] Keeping workflow alive for 1 hour..."
          sleep 3600

          echo "[INFO] Workflow finished"
